settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Eden Yavin # [First Name(s)] [Last Name]
  links:
    # Personal Blog
    - https://www.linkedin.com/feed/update/urn:li:activity:7289536068645720064/
