settings:
  docker:
    parent_image: 225989347471.dkr.ecr.eu-west-1.amazonaws.com/zenml-apqxcl:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Eden Yavin # [First Name(s)] [Last Name]

  interested:
    - LLM
    - cybersecurity
    - agents

  platforms:
    - arxiv
    - github


