settings:
  docker:
    parent_image: 225989347471.dkr.ecr.eu-west-1.amazonaws.com/zenml-apqxcl:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  requesters_full_names:
    - Eden Yavin
#    - Maxime Labonne
#    - Paul Iusztin
